version: "3.8"
services:
  php-apache-environment:
    container_name: weight_apache
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 7007:80